README.md

Added IPFS-Store to middleware section and updated Eventeum description.

IPFS-Store addition and Eventeum change

---

README.md

Solidity (for now) graph debugger

Adding ethereum-graph-debugger

---

README.md

Added MyCrypto and explained different things you can do with it.

Added MyCrypto

---

README.md

- [Ropsten faucet](http://faucet.ropsten.be:3001/)

Add Ropsten faucet

---

README.md

- [Ethereum Development with Go](https://goethereumbook.org/)

Add DApp development section

---

README.md

adds incentive tools

---

README.md

Added SmartCheck - tool for static analysis of Solidity source code for security vulnerabilities and best practices.

Added SmartCheck

---

README.md

This collection will:
- provide a reference and learning materials of common bugs in ERC20 token contracts
- help ERC20 token contract developers to develop correct and secure contracts
- notice DApp developers of incompatible/buggy/vulnerable ERC20 token contracts
- warn exchanges and investors of potential risks in incompatible/buggy/insecure ERC20 tokens

add "Awesome Buggy ERC20 Tokens" repo from SECBIT

---

README.md

I am submitting my npm package to this list. I have been developing smart contracts for the last year and wrote this. It parses a local testrpc's transactions.

add decode-eth

---

README.md

Simply added Superblocks Studio to the list of IDEs

Added Superblocks Studio to the list of IDEs

---

README.md

Added LedgerDex to list of 0x protocol based decentralized exchanges. Information can be verified at: https://0xproject.com/wiki#List-of-Projects-Using-0x-Protocol

Added LedgerDex to list of 0x protocol based decentralized exchanges

---

README.md

added open source IDE plugin IntelliJ-Solidity

added open source IDE plugin

---

README.md

- Add Short description
- Add link to Truffle demo
- Add link to Embark demo

Add Vortex to README.md

---

README.md

I just realized there was a small formatting issue (wrong indentation) with the new LedgerDex listing I just added. Now It's been fixed. Sorry about that! Thanks!

fixed indentation issue with the LedgerDex listing

---

README.md

I added Pragma to the list of IDE's (www.withpragma.com)
It is a super beginner-friendly way to write smart contracts, view event logs, and share a link with an interface to your contract.

Update README.md to include Pragma

---

README.md

Added link to [ether_sql](https://github.com/analyseether/ether_sql)

Added ether_sql

---

README.md

Adds the subproviders package to the `Tools` section.

Add subproviders package

---

README.md

Hey! We have a new website for all our developer tools, so I updated the link for dapp.

Updated link for dapp

---

EcosystemResources.md

Adds a link to Solidity cheat sheet i recently created when learning Solidity. It might help someone to get overview of what's possible or help new developers at the start of their learning

Add Solidity cheat sheet to resources

---

README.md

This repository collects correctness proofs of Ethereum token contracts wrt. given specifications and high-level properties. All of them are accomplished in Coq. Currently, an ERC20 token contract and its proof are included, but more will be added in the future.

add tokenlibs-with-proofs

---

README_Korean.md
Tools_Korean.md

Hello guys,
I translated Tools.md file using my free time.
I didn't add the project and/or tools.
Just translated it.
I will try to translate EcosystemResources.md file later.
Have a good day~

Translate Tools.md to Korean

---

EcosystemResources.md
Tools.md

Fixes to existing blog links and additions with relevant content.

Add and fix Aragon related links and entries

---

README.md

Fix py-eth link

---

README.md

Updated the README.md file to include a link for TEMPORAL, an API/Interface for IPFS, and other decentralised/distributed storage protocols.
Current support is for IPFS on the public swarm, as well as support for private IPFS swarms. Additional protocols such as STORJ, SIA, and SWARM (Ethereum) are being worked on.

Add TEMPORAL, an easy to use API/Interface for IPFS and other storage protocols

---

README.md

Fix EthSum link

---

README.md

`solhint` is a linter for solidity, `eth-cli` is CLI tool that allows doing several ethereum-related things from the command line.

Add solhint and eth-cli

---

EcosystemResources_Korean.md
README_Korean.md

Hey,
as you can see, translate complete to last commit.
Have a good day~

Translate updates

---

README_Japanese.md

Hi guys, I'm really appreciated to your work for this list!
I translated your awesome work to Japanese.
I hope that merge it to master branch if you can.
Regards 😉

add README_Japanese.md

---

EcosystemResources.md

`Nifty Wallet` is an Ethereum Browser Extension focused on usability of real world applications

Add Nifty Wallet

---

README.md

SmartCheck (https://tool.smartdec.net/) is a free static Solidity code analyzer. Added to the list of security tools.

Add SmartCheck security tool

---

EcosystemResources.md

Small fixes

---

EcosystemResources_Japanese.md
README_Japanese.md

I translated EcosystemResources.md to Japanese.
Similar work as #106 
Regards :D

Translated EcosystemResources.md to Japanese.

---

README.md

I think Flint is an interesting language proposal for writing smart contracts and should be included in this list

Include Flint smart contract language

---

README.md

Parasol is an Agile Smart Contract Development Environment that follows three principles:
Most existing development environments are designed for dApps, not for smart contracts. Developers are restricted to the Migration smart contracts design pattern as required by other development environments to facilitate dApp versioning. Parasol puts into consideration developers who intend to develop pure smart contracts and avoids restricting them to a specific dApp design pattern.
Parasol aims to implement as little abstraction on top of its dependencies as possible. It provides direct configuration access to its core components such as solc and ganache. Additionally, it allows the user the freedom to customize and contract deployment logic through the deployer() function in the configuration …

Added Parasol

---

README.md

Psol is the first ever Solidity lexical preprocessor. It is a minimal 40-line module powered by underscore.template. Psol was developed for Parasol 2.0 but it is also a standalone package which can be used directly with solc.
Features and usage at the Github repo: https://github.com/Lamarkaz/psol

Added Psol

---

README.md

I have made a small service: https://flightwallet.org/decode-eth-tx
It can decode and publish raw ethereum tx. Helped me a lot!

Add Decode and Publish page

---

README.md

Add web3x, a TypeScript port of web3.js

Add web3x, a TypeScript port of web3.js

---

README.md

https://github.com/merklejerk/solpp

+solpp, a preprocessor and flattener for solidity

---

README.md

- [slither from trailofbits](https://blog.trailofbits.com/2018/10/19/slither-a-solidity-static-analysis-framework)
- [adelaide from SECBIT](https://github.com/sec-bit/adelaide/blob/secbit-ssae/README.secbit.md)
Smart contract developers could use static analysis tools during the development life cycles to find bugs in their code easily. Static analysis tools are also useful to code auditors.

adding two static analysis tools for Solidity

---

EcosystemResources_Korean.md
README_Korean.md

Hey~
It's been a while.
I updated it the same way.

Updated Translate Korean Documents

---

README.md

Added some tools and fixed some linking. Change-set looks self-explanatory.

added tools and fixed linking

---

README.md

As the title suggests, added Tenderly to the list of testing tools.

Added Tenderly to the testing tools list

---

README.md
README_Japanese.md

getho is a DApp development platform. It has 
- Launch your own private node by just few clicks and get its HTTP Endpoint.
- When you deploy your smart contract to getho, you can run functions on GUI.

Added getho

---

README.md

As title suggests, added Chainlyt to the monitoring section.

Added Chainlyt to monitoring 

---

README.md

Good source of Ethereum info, especially eth 2.0

Adding EthHub Documentation

---

README.md

Modern, noob-friendly (less boilerplate) frontend libraries.

Add flex-contract, flex-ether, and ez-ens JS libs.

---

README.md

Added Rimble Design System to Readme

---

EcosystemResources.md
README.md

The commit messages within this PR should sufficiently convey each of the proposed changes.
For disclosure, I work for Oraclize.

fixes and additions regarding Oraclize

---

README.md

I am not sure if this is in the appropriate section, nor am I sure my thing is appropriate to include.  However, I figured I should give this a shot.  Let me know if another section is more appropriate?
Also, do you think any of my libraries would be useful to include somewhere?  You can find them all on my profile: https://github.com/eth-button

Add reference to eth-button

---

README.md

- Also some small fixes on other Aragon dev tools referenced throughout

Add aragonPM - decentralized package manager

---

README.md

Fortmatic (presenting sponsor at ETHDenver 2019) is an amazing and easy to use SDK for beginners to start playing around with Ethereum. It abstracts the complexities with dealing with the blockchain but allows developers to build dApps and focus more on UX and the economics of the app.

Added Fortmatic to new developer section

---

README.md

As the title suggests: added Tenderly to the list of monitoring tools.

Added Tenderly to the list of monitoring tools

---

EcosystemResources.md

Hello,
I added these 3 projects/tools:
- ETHLend platform, decentralized lending marketplace - https://ethlend.io/
- Aave Pay Service to pay in fiat with cryptocurrencies - https://pay.aave.com/
- Aave SDK Tools to integrate Aave services - https://github.com/aave/aave-js

Addition of ETHLend and Aave

---

README.md

BlockScout is an open source full featured EVM block explorer which would make a good addition to this tools list. 
Features:
* Blocks
* Transactions
* Account Balance History
* ERC-20 & ERC-721 Support
* Contract Verification
* Uncle and Reorg Support
Clients Supported:
* Geth
* Parity
* Ganache

Add BlockScout EVM Explorer to Tools list

---

README.md

ZeppelinOS is a framework, similar to Truffle and Embark that allows you to create entire smart contract applications. ZeppelinOS furthermore allows users to build upgradable smart-contracts and manage on-chain code libraries in the form of EVM packages.

Added ZeppelinOS as Development Framework

---

EcosystemResources.md

feel free to ask any questions !

Add Rockside.io under Services

---

README.md

Delphereum is a web3 implementation for the Delphi programming language.

Added Delphereum to the frontend Ethereum APIs

---

EcosystemResources.md

* Added [Nodesmith](https://nodesmith.io) which provides JSON RPC APIs for connecting to Ethereum mainnet and testnets

Addition of Nodesmith

---

README.md

It is new development environment framework for Ethereum blockchain.

Added Cobra framework

---

README.md

Add Ethereum services:
- Service to interact with smart contract
- Service to interact at low-level with Ethereum
Add Plasma services:
- An application that automatically challenges invalid exits
- Service that exposes and notifies events and API of the OmiseGo network

Add MESG Services

---

README.md

Author said [Populus](https://github.com/ethereum/populus) is no longer maintained.

Replace Populus to Brownie

---

EcosystemResources.md
README.md

I've gone through every link in the repo and made a note of broken ones and whether they have a replacement, and either replaced the link, or removed the listing if there didn't seem to be a suitable source. I've also added the metamask mobile wallet to the list of mobile wallets, I'm sure everyone's familiar enough with metamask that I don't have to explain why.

Fix broken links

---

README.md

Added Piet, a Solidity architecture analyzer. It parses solidity code, provides graphical representations of smart contract architecture & supports interaction with smart contracts. More information: https://blog.slock.it/analyzing-solidity-smart-contracts-with-piet-6db33a733e79

Added Piet

---

README.md

Request to add the Nightfall repo to the developer-tools-list please.

doc: add nightfall

---

EcosystemResources.md
README.md

- Add Chainstack to Test blockchain networks
- Add Chainstack to Ethereum Clients
- Add Chainstack to Services in Ecosystem Resources
- Add Chainstack Docs to Knowledge/Education in Ecosystem Resources

Add Chainstack

---

README.md

Added a few new tools for the list.  Please let me know if any don't meet the standards and I can get them removed.  Thanks!
- Marmo
- Azure Blockchain Dev Kit for Ethereum
- Cloudflare's Ethereum node service
- Terminal

Added Marmo, Azure EthKit, Cloudflare, Terminal

---

README.md

> [Kauri.io](https://kauri.io/) - A community based knowledge platform for web3 and emerging technologies. Share curated content and collaborate on up-to-date and high-quality technical articles and series. Checkout the [Getting Started community](https://kauri.io/community/5d9b16fc890d310001b66e1b) to learn the basics.
I believe kauri.io has a lot of great content for new developers. The [Getting Started community](https://kauri.io/community/5d9b16fc890d310001b66e1b) is updated regularly with quality content posted by the members.
That's why I think it can be placed in the **New developers start here** section

Add kauri.io - Getting started

---

README.md

3Box have a number of tools which are relevant to DApp developers
- User controlled storage
- Messaging API
- React plugin Components

Adding 3Box

---

EcosystemResources.md

Hi There,
Just adding reference.auditless.com under the reference section, hopefully helpful for people looking to compare/learn Solidity & Vyper :).

Adding the side-by-side Solidity & Vyper cheat sheet

---

README.md

Added three new libraries: Ethereum-watcher, Ethereum-tx-sender, and Ethereum-jsonrpc-gateway along with descriptions.

Adding Eth watcher, tx sender, jsonrpc-gateway

---

README.md

Add Ethcode link & descriptions under IDEs

Add Ethcode

---

README.md

@maticnetwork is a sidechain based scaling solution for public blockchains. It is based on an adapted implementation of Plasma framework. Matic provides scalability while ensuring a superior user experience in a secured and decentralized manner.

Add Matic Network

---

README.md

Biconomy is a relayer infrastructure network and transaction platform enabling you to build applications easily and reduce the friction between your applications built on the blockchain and your end-users.

biconomy added

---

README.md

Creating a new category to help resolve #51 
Also adding my own project, rTrees, which is totes amazing.

Add "Dapps" category

---

README.md

This pull request adds Pinata (https://pinata.cloud) to the list of IPFS service providers

Add Pinata to list of IPFS providers

---

README.md

This website offers a lor to great tutorials for Solidity beginners and advanced programmers.

Added EthereumDev as a tutorial resource

---

EcosystemResources.md
README.md

- Removes extra indentation for Frontend Ethereum APIs
- Moves create-react-app to FE section

Cleanup fixes

---

README.md

Adds the Diamond Standard as one of the contract patterns.

Added Diamond Standard

---

EcosystemResources.md
README.md

Hi!
Big fan of this list, its rare to find something so comprehensive. Would love to add Torus to the list, we help apps have a seamless UX utilizing dkgs for key management

Add Torus SDK to build Dapps with a seamless UX

---

EcosystemResources_Chinese.md
README_Chinese.md

I added a Chinese version, I hope more Chinese programmers can see it.

add Chinese Doc

---

README.md

[Create Eth App](https://github.com/paulrberg/create-eth-app) is a tool for creating Ethereum-powered frontend apps with one command.

Add Create Eth App

---

README.md

Rename Buidler to Hardhat

---

README.md

Aleph.im is a unique blend of onchain and offchain decentralized technologies. Compatible with Ethereum of course.

Add aleph.im

---

README.md

Updating this to be reflective of the latest in Blocknative's portfolio.

Blocknative Updates

---

README.md

Added alternative Ropsten Faucet

Add Alternative Ropsten Faucet

---

README.md

Adding two resources to the list. 
* [Clean Contracts - A guide to writing clean code](https://www.wslyvh.com/clean-contracts/)
* [ETH Gas.watch](https://ethgas.watch/) - A gas price watcher with email notifications on price change

Adding two resources

---

README.md

Add Online ABI encoder tool github source link in "Ethereum ABI tools" section

Add Online ABI encoder

---

README.md

Added a tool to:
1) Create a shareable contract dashboard
2) Interact with an arbitrary function in any EVM-based blockchain
Both with or without an ABI.

Add EVMConnector, to interact with arbitrary contracts

---

README.md

Adding useWeb3.xyz - A curated overview of the best and latest resources on Ethereum, blockchain and Web3 development.
This repo is also linked on there :) 
https://www.useweb3.xyz/websites

Update README.md - adding useWeb3

---

EcosystemResources.md

I added a jobs section with list of websites where you can find a job (ConsenSys,  Ethereum Foundation, Web3Jobs)

Added jobs section

---

contributing-criteria.md

Adapted the markdown formatting in `contributing-criteria.md`

Correct markdown formatting

---

EcosystemResources.md
README.md

Add Watchdata to services, Test Blockchain Networks, Backend Ethereum APIs

Add Watchdata to services, Test Blockchain Networks, Backend Ethereum APIs

---

README.md

Was not sure if it belongs to out-of-box tools or ABI tools

Add contract-admin tool

---

README.md

Added Forta to the monitoring section

Added Forta

---

README.md

Transpose provides complete low and high-level data (blocks, transactions, assets, wallets) on Ethereum, with keys available for free.

Adds Transpose to data provider API list

---

README.md

https://raid-guild.github.io/quiver/

Add Quiver

---

README.md

Adding [Blocktorch](https://blocktorch.xyz) to monitoring tools

Adding Blocktorch to monitoring tools

---

README.md

Web3 Security Scanner Aggregator. It performs on-chain smart contract audits for several blockchains: ethereum, bsc, polygon, arbitrum and avalanche.

Added smackmycontract.xyz in [Security]

---

README.md

A free, open-source platform working to aggregate all Smart Contracts and EVM libraries

Adding Cookbook.dev

---

README.md

Sidekik is a new dev tool that lets developers inspect, interact, and understand smart contracts. Grew out of an internal dev tool that was recently released. It's free to use as a client-side web application.

Update README.md to include Sidekik for monitoring and ABI inspection

---

EcosystemResources.md
README.md

Chainnodes is an EVM blockchain node provider. I added it to the list of services. How should I deal with the translations?

feat: add Chainnodes to infra provider list

---

EcosystemResources.md
README.md

L2BEAT is an analytics and research website about Ethereum layer two (L2) scaling solutions. 
https://l2beat.com/
I consider this website a good starting point for person trying to learn about Layer2 ecosystem.

Add L2Beat

---

README.md

Added Arweave and Bundlr to the Storage solutions section

Added Arweave and Bundlr

---

README.md

Added Fe-Lang to Smart Contract Languages

Added Fe-Lang to Smart Contract Languages

---

README.md

Online Solidity ABI Encoder to encode smart contract arguments, and also perform read and write operations on the blockchain.

Online Solidity ABI Encoder

---

README.md

Added web3client in IDEs list.
Kindly, feel free to comment or reject my PR if it is not standard to the repo.

Added Web3Client

---

README.md

add db3 network to readme

---

README.md

This pr adds Huff to the list of "languages"

docs: add Huff language

---

EcosystemResources_Chinese.md
EcosystemResources_Japanese.md
README.md

Ramen is an Ethereum TUI, I think it fits into out-of-box tools that communicates with Ethereum.
repo: https://github.com/dyng/ramen

Add ramen to out-of-box tools

---

README.md

Basement is a tool for onchain data. It's GraphQL API is free without an API key, and the other tools are free to try with an account.

Add Basement

---

README.md

Hi - I'm requesting to add our company, GuardianUI, to this section. Thank you.

Add GuardianUI to Monitoring Section

---

README.md

[Tools for Solidity](https://marketplace.visualstudio.com/items?itemName=AckeeBlockchain.tools-for-solidity) is a VS Code extension that provides common language server features for Solidity (Go to definition, Find all references, Rename, etc.) but also offers live vulnerability/code quality detectors that refresh after every keystroke. It has support for Foundry (the command `Tools for Solidity: Import Foundry Remappings`) and can generate useful graphs (inheritance graphs, control flow graphs, import graphs).
It differs from other extensions in that it relies on compiler output, which guarantees LSP features work correctly (in comparison to using just Solidity parsers).

📝 Add `Tools for Solidity` extension

---

README.md

Added a couple of tools by Pessimistic Security:
- **Slitherin** to the Security Tools section
- **Pessimistic Spotter** to the Monitoring section
Looking forward to your response.

Added Slitherin and Pessimistic Spotter

---

README.md

Tool have Python & JavaScript implementations, [reproducable](https://github.com/cdump/evmole/tree/master/benchmark) [benchmarks](https://github.com/cdump/evmole/#benchmark) and [online demo](https://cdump.github.io/evmole/).

Add EVMole function selectors extractor

---

README.md

Adding a few tools for account abstraction onboarding/adoption:
- wallet-login-sdk - Smart Wallet SDK focused on onboarding via email, supports the popular EVM chains.
- signature-validator:  TypeScript library that universally validates account abstraction (ERC-6492, ERC-1271) signatures, as well as traditional EOA signatures. Also has EIP-712 support.

Add signature-validator, login-sdk

---

README.md

Find more about the project here:
https://github.com/tradingstrategy-ai/web3-ethereum-defi

Added Web3-Ethereum-Defi in backends

---

README.md
README_Chinese.md
README_Japanese.md
README_Korean.md
README_Spanish.md

docs: add Holesky faucet

---

README.md
README_Chinese.md
README_Japanese.md
README_Korean.md
README_Spanish.md

This PR adds [Kontrol](https://github.com/runtimeverification/kontrol) to the Security Tools list. 
Kontrol is a formal verification tool for Solidity smart contracts that utilizes Foundry property tests augmented with [additional cheatcodes](https://github.com/runtimeverification/kontrol-cheatcodes) for verification, and is an integration between [KEVM](https://github.com/runtimeverification/evm-semantics) and [Foundry](https://github.com/foundry-rs/foundry).  Documentation is available at https://docs.runtimeverification.com/kontrol/overview/readme.

Add Kontrol to Security Tools

---

README.md

ERCx checks the conformance of a contract to [ERC (Ethereum Request for Comments) standards](https://eips.ethereum.org/erc). ERC standards exist for various sorts of tokens, fungible or not. ERC standards specify essential aspects of a contract (management of transfers, delegation, etc.). Contract developers should strive to follow the guidelines of ERC standards as they provide a reference frame during development.
https://ercx.runtimeverification.com

Add ERCx Testing and Security tool

---

README.md

Adding Tatum as a blockchain development tool that  streamlines building web3 apps.

Adding Tatum as a blockchain development 

---

README.md

Add GhostGraph: create EVM chain indexers using Solidity
**Website:** https://ghostgraph.xyz
**Docs:** https://docs.ghostlogs.xyz/ghostgraph/overview/

Add GhostGraph: create EVM chain indexers using Solidity

---

README.md

Ethereum Studio no longer exists

Removed Ethereum Studio

---

EcosystemResources.md

Free courses, ideal for beginners.

Add Bankless Academy to Education ressources

---

README.md

FIx typo Update README

---

README.md

> WeaveVM is a sovereign EVM rollup built towards the goal of solving the EVM storage dilemma with [Arweave](https://arweave.org/). It gives the coming generation of high-performance chains a place to settle and store onchain data, without worrying about cost, availability, or permanence.
- [WeaveVM](https://wvm.dev)
- [Docs](https://docs.wvm.dev)

Add WeaveVM to storage infrastructure

---

README.md
README_Chinese.md
README_Japanese.md
README_Korean.md
README_Spanish.md

Adding evmtools (a toolkit for web3 and solidity developers) to the readme list.

add evmtools to the dev tooling list

---

EcosystemResources.md
README.md

Hello
I fixed several spelling issues in order to ensure a better understanding.
Br, Elias.

docs: fix spelling issues
