README.md
I added some links to web3.js and ethers.js. I saw they were in the front end library section too. Just thought it would be nice to link them in both sections. I also changed the drizzle link to the library repo instead of the truffle-box repo.
Let me know if you don't agree with those links. I also found web3.js readthedocs, but it seemed out of date. I found Ethers.js [docs site](https://docs.ethers.io/ethers.js/html/) if that is preferred.
- Updated Web3.js in programming languages section
- Updated Ethers.js in programming languages section
- Changed Drizzle link to point to the drizzle repo instead of the truffle-box
- Fixed some hyphens
=> Updated some links

README.md
Include the OrbitDB database [https://github.com/orbitdb/orbit-db](https://github.com/orbitdb/orbit-db)
=> Include OrbitDB (decentralised DB on top of IPFS)

README.md
It doesn't really fit into 'Wallets'. The closest category is Block Explorer, but I think a new category makes sense
=> Moved EthGasStation from Wallets to new category 'Gas Price Calculators'

README.md
Add link to `www.py-eth.com`: a collection of tooling built in Python for the Ethereum ecosystem.
=> Add py-eth to developer ides and tools

README.md
Removing "Solutions PoC starter app" from "Bootstrap" section: The link to the project is broken: this project was probably deleted (or moved, but impossible to find the new repo)
=> Removing "Solutions PoC starter app"

README.md
Yesterday we released the full version of a new security scanner: https://securify.ch
Should be added to the list.
=> New security scanner: https://securify.ch

README.md
truffle-flattener
* https://github.com/alcuadrado/truffle-flattener
* https://www.npmjs.com/package/truffle-flattener
Truffle Flattener concats solidity files developed under Truffle with all of their dependencies.
I have used for several months with great success.
=> Adding truffle-flattener

README.md
EthSum is a web Ethereum address checksum tool and I'm its author. It's handy to have it in the browser, as not all exchanges or dApps verify the checksum.
=> Added EthSum

Tools.md
Ethereum on Azure allows you to configure and deploy a PoA test network in Azure cloud.
=> Adding Ethereum on Azure to test net list

README.md
I'm not affiliated with the guys who made Ethereumex, but think it should be on the list.
Also added a EthContract - helper library for calling smart contracts.
=> Add Elixir libs to the list of Backend Ethereum APIs

README.md
Minor corrrection. Separated Loom Network as they are not part of POA.
=> Loom and POA are different networks. Loom is not part of POA

README.md
- Updated the name from Superblocks Studio to Superblocks Lab (new name)
- Updated description to a more specific feature set (instead of a more generalistic description)
=> Updated Superblocks Studio to reflect 1.0 release (including a rename)

README.md
I added my `truffle-assertions` library, which is used mainly to assert that specific events with a specified event type have been emitted. The library also takes a filter function on the event arguments, allowing the developer to make the assertions as coarse or as fine-grained as needed.
=> Added truffle-assertions

EcosystemResources.md
Linnia has a new name, Stow.  Also linnia has a new website
=> Updating name of Linnia to Stow

README.md
* [ethnode](https://github.com/vrde/ethnode) - Run an Ethereum node (Geth or Parity) for development, as easy as `npm i -g ethnode && ethnode`.
=> Add ethnode to "test blockchain networks"

README.md
As the title suggests, Tenderly has moved to the `.dev` domain.
=> Switched Tenderly URL to the new domain

README.md
[sbt-ethereum](https://www.sbt-ethereum.io) is an open-source Ethereum development and interaction framework I've been working on for a while. Would it be suitable to add to the frameworks list?
Many thanks.
=> Add sbt-ethereum to frameworks list.

EcosystemResources.md, EcosystemResources_Japanese.md, EcosystemResources_Korean.md, README.md
As Oraclize has rebranded to Provable, it would be useful to update instances of Oraclize here to avoid confusion. 
Attempted phonetic transliteration of Provable for Korean, which it appeared to be the case with Oraclize, should be sufficient in current state but probably best checked by a Korean speaker.
=> rebrand instances of Oraclize to Provable

README.md
Solc-verify is a modular verifier for Solidity built on top of the Solidity compiler. For more info see:
- Paper: https://arxiv.org/abs/1907.04262
- Readme in the repo: https://github.com/SRI-CSL/solidity/blob/boogie-devel/SOLC-VERIFY-README.md
=> Added solc-verify

README.md
The tool I previously developed under the name of Vortex is now known under the name of ethvtx.
This PR updates its info in the english README.md
=> fix: rename Vortex to ethvtx and update links

EcosystemResources.md, EcosystemResources_Japanese.md, EcosystemResources_Korean.md, README.md, README_Japanese.md, README_Korean.md
Added dfuse, a blockchain APIs service company that provides powerful detailed API to retrieve and consume data from Ethereum blockchains (and others).
We offer a GraphQL query & subscription based operation to search the entire chain while only giving you the transactions you only care about using a simple GitHub like query language. You get the most detailed view the transaction being able to track inner contract EVM calls, balance changes, state changes and more.
=> Added dfuse, a blockchain APIs service company

README.md
QuikNode API = free access to ETH MainNet for dev, or users can upgrade to a dedicated node (Geth or Parity)
=> update infrastructure, add quiknode.io

README.md
It seems the flint and bamboo language development have been discontinued.
Last commits on both date back to almost a year.
=> Update Smart Contract languages List

README.md
truffle-plugin-verify allows you to verify your smart contract source code on Etherscan with a single command from the Truffle command line. Couldn't be easier!
```
truffle run verify SimpleStorage --network rinkeby
```
=> Add truffle-plugin-verify

EcosystemResources.md
Chainshot courses are paid. Their bootcamp link is https://www.chainshot.com/bootcamp This link does not mention the rates but when I submitted an application they informed me about the rates.
=> Chainshot Building blocks in Knowledge/Education

contributing-criteria.md
As the pull requests pile up, and as contributors may have motives that stray from the purpose of helping other developers (promotion, spam, etc.), I wanted to start a conversation on what the criteria should be for accepting new contributions. 
To start it off, here are some things I thought of:
* What falls under the scope of developer tools? If it's outside (e.g. DApps) should we include a separate heading for well-built DApps that aid people's understanding of them
* Should proposed tools have met a certain threshold of usage? Could this be captured in a number of Github stars or forks?
* Should repo maintainers be required to use and evaluate the tools before adding/removing from the list?
* What reasons/feedback should be provided by maintainers if a proposed tool is rejected?
These …
=> request for comments on contributing standards and acceptance criteria

EcosystemResources_Spanish.md, README_Spanish.md
This pull resolves issue #118
Some words where left in English as they don't have a proper translation in Spanish:
-  "pull request". Reference: angular/angular-es#38 (comment)
- "framework". This word is used in this way most of the time, other wise could be confuse. Also Wikipedia uses it in such a way too, further pushing the convention among Spanish speakers.
- "Frontend". Translation "Interfaz de Usuario" means "User Interface", which is a more general concept for Spanish definitions and academic books in Computer Science.
- "Backend". Translation could be confused with "server" or "app code", which now days is wrong, as the server could mean frontend too. Almost all IT understand these two words.
- "bootstrap". No proper translation.
- "crowdsourced". No proper translation.
- …
=> Add spanish translations

.github/workflows/checks.yml
Because this list was compiled over several years, some of the links in this list are now broken. This PR uses [github action markdown link check](https://github.com/gaurav-nelson/github-action-markdown-link-check) to check for broken links. After broken links are identified, the next step can be to remove or fix the links.
Because there are broken links, this PR will cause the CI system to trigger a failure on future PRs until the links are fixed. This can be changed by modifying the `on: [push, pull_request]` line to `on: [push]` to avoid running this action on PRs.
=> Add CI check for broken links

README.md
The ETHCode vscode link was broken, just fixed it now. 
Please let me know if that is the correct link for the extension.
=> ETHCode Link Broken

README.md
OpenZeppelin Starter Kits has been deprecated. [Starter Kits](https://docs.openzeppelin.com/starter-kits/)
Link  provided was dead [Starter Kits](https://openzeppelin.com/starter-kits/).
Replaced link with suitable OpenZeppelin replacement, OpenZeppelin Wizards, which walks a new developer through creating an OZ contract.
=> removed Openzeppelin Starter Kit Link

README.md
This PR is to add the Smart Contract GUI to ABI tools.
The Smart Contract GUI is a battle-tested tool that is built and maintained by [Massless](https://massless.io). It has been used for integration testing across many major projects with smart contracts totaling over $25million in revenue.
We have found the Smart Contract GUI invaluable and we can't think of a better way to give back to the awesome web3 community than by providing access and support for free.
=> Add Smart Contract GUI to ABI tools

README.md
Ethereum datafarm was mainly created with the focus to enable economic/business students (who do have the knowledge to to quantitative analysis on cryptocurrencies but lack of CS knowledge to scrap data from the chain) easy access though a wrapper around the Etherscan api.
For example, users can plug in the uniswap contracts, parse the event data and use the information to do further price analysis.
I have received great feedback so far and I think the tool may provide many people access to Ethereum!
=> Add ethereum-datafarm

README.md
SNS module for Push Delivery Nodes allows any developer to receive notifications, chats, or any other form of web3 communication directly to the platform they are building with the help of webhooks.
Hosted SNS Module is a mid-level solution that eliminates all the heavy load of running a node or syncing information and gives you webhooks that you implement to start receiving notifications, chats, or any other web3 communication in your software.
Ethereum Push Notification Service (EPNS) is the world’s first decentralized communication & notification protocol for Web3.
Using the protocol, any smart contract, dApp, or backend service can send on-chain or off-chain notifications tied to the wallet addresses of users in a gasless, multichain, open, and platform-agnostic way.
Being an open …
=> Add EPNS SNS Notifications

README.md
There are some typos in the README file
**Changes:**
"mentionned" -> "mentioned" 
"distrubuted" -> "distributed"
"Visualise" -> "Visualize"
"Recieve" -> "Receive"
"standarize" -> "standardize"
"utilising" -> "utilizing"
=> Fix typos in README file 

README.md
Remove reference to ethereumdev.io as the domain is no longer valid and no longer in use.
=> Remove reference to non-valid ethereumdev.io domain

README.md
This PR adds 
1. A category called distribution. As the dApp ecosystem continues to grow, this category will become important and have more tools coming in.
2. Meroku as the first tool in this category.
=> Adding distribution category and Meroku as a tool

README.md
[Rinkeby and Ropsten are going offline](https://blog.ethereum.org/2022/06/21/testnet-deprecation) so I think its a good idea to show a deprecation message in the faucets of those networks
=> Deprecation message in Rinkeby and Ropsten

README.md
Add [Catapulta](https://catapulta.sh/) smart contracts platform, a tool for deployers to automatize manual steps in the deployment process of smart contracts, for Foundry and Hardhat. Is a freemium tool.
=> chore: add Catapulta to frameworks list

README.md
ETHGas.watch no longer exists and has been migrated and redirects to ETH Gas Tracker.
Updating so the correct domain is in the list
=> Update ETH Gas tracker

README.md
It's a tool which display calldata in clear and interactive manner.
https://purrproof.github.io/calldata-visualizer/
=> add Calldata Visualizer link to Ethereum ABI tools section

README.md
Add the ERC-1363 Token Standard. 
[ERC-1363](https://eips.ethereum.org/EIPS/eip-1363) is an extension interface for ERC-20 tokens that supports executing code on a recipient contract after transfers, or code on a spender contract after approvals, in a single transaction.
=> feat: add erc1363
